trigger:
- main

pool:
  name: mika-pool

variables:
- group: my_tokens

steps:

- script: |
    az login --identity
  displayName: 'Authenticating with Managed Identity'

- script: |
    echo "Retrieving secret from Key Vault..."
    secret=$(az keyvault secret show \
      --vault-name "mikaKeyVault1" \
      --name "SuperSecret" \
      --query "value" -o tsv)

    echo "##vso[task.setvariable variable=SuperSecret;issecret=true]$secret"
  displayName: 'Get Secret from Azure Key Vault'

- script: |
    echo "Secret is: $(SuperSecret)"
  displayName: 'Use Retrieved Secret'

- script: |
     sonar-scanner -Dsonar.login=$(SONAR_TOKEN)
  displayName: 'run SonarCloud'

- script: |
    echo "==>Build Docker Image"
    docker build -t myapp ./app
  displayName: "build  Image"

- script: |
    echo "==> (unit-tests)"
    python3 ./app/test.py
  displayName: "test app"

- script: |
    docker tag myapp mikaregistry2025.azurecr.io/myapp:$(Build.BuildId)
  displayName: "Tag Docker image"

- script: |
    echo "$(ACR_PASSWORD)" | docker login mikaregistry2025.azurecr.io -u "$(ACR_USERNAME)" --password-stdin
    docker push mikaregistry2025.azurecr.io/myapp:$(Build.BuildId)
  displayName: "Push image to ACR"

- script: |
    sed -i "s|image: mikaregistry2025.azurecr.io/myapp:.*|image: mikaregistry2025.azurecr.io/myapp:$(Build.BuildId)|" ./k8s/deployment.yml
  displayName: "Update image version"

- script: |
    git config user.name "mika"
    git config user.email "mika@ci"
    git add ./k8s/deployment.yml
    git commit -m " Update deployment to image tag $(Build.BuildId) [skip ci]"
    git push origin main
  displayName: "Update deployment with new image tag"

- script: |
    kubectl apply -f ./k8s/deployment.yml
  displayName: "Deploy to AKS"
