---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: the-secret
  namespace: default
spec:
  encryptedData:
    mika: AgAEPRLTIVBINWshk5YGQcr6ErkmCziVxkNH0YgFVAe6vHguvUWNRl6ofqhrbV44O8TAsKsMrDdvzWbgxWwouUZn/4H1EHSPsy94CACrOY+cEQ/fD+Bxq6mO3Ux93pJo2k+vWfHLqzYP+QO0qC9pZ/sLEe1kWKlDSIw80eAaOO7TtO6ml/hxkw5l4mDpV8z/kWS+Qqm8ELn+wbixeiWhg3tuHqC5kNndhz5ouKl6zIdMcniiTnKyODQ18ZgtkWp0tIM3ncoCXDRngJiRxKSTPmmcWITa8v5XR/U463HOyZxJvvSTbconDw+tBTX0wMm5Zut/NC+4qK9+L7U8DkjJX5f8sS928jErvoGWNfvRHIDIsjS/9jjI8WCbhZpZEsh4dq2sLj36HeczCYL21W9duo9vrCG8cj1dnKfUZRBUF6E8e0iacsN8+YFh5uHwZPAJAf2e9bQYDCVLizK76Az8c52gQPWF8WqjR9NEKQY9K5a3YtAPTA1I6n2W+BiXTrqiqqe1h132RpZi3AjFT64T2/TPsWFQe6M9J65Oq+vjMzefdhaGDxPLwepjtQQowU20XdN0jKgoL4fug8jJJCMFt+ntevt2CQ37GSDRuM84JW8rPWrSlWydNgkIyl0D5yIeUjShxw06FRL0g3tQrkGhGqhUX6mUJXNJtkbXpG2rEK2fFXJ0hrgZzZw0VU8OBV2N4wJELambgQ==
  template:
    metadata:
      creationTimestamp: null
      name: the-secret
      namespace: default
